// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz5nVQH7SCw0u2qGY_bRiw-HxTlg2Hg8w',
    appId: '1:763423081284:web:710c7a8e1f7da8031e4d11',
    messagingSenderId: '763423081284',
    projectId: 'lhp-chat-app',
    authDomain: 'lhp-chat-app.firebaseapp.com',
    storageBucket: 'lhp-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA79qsljOaSmt5wBy99qy6pfUZDLjMlu5c',
    appId: '1:763423081284:android:3ceb29d224f6189d1e4d11',
    messagingSenderId: '763423081284',
    projectId: 'lhp-chat-app',
    storageBucket: 'lhp-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnP477Sva9d30iAkKRUd_PbEKbXeCVc5g',
    appId: '1:763423081284:ios:87e81320a62881c11e4d11',
    messagingSenderId: '763423081284',
    projectId: 'lhp-chat-app',
    storageBucket: 'lhp-chat-app.appspot.com',
    iosBundleId: 'com.example.myChatApp',
  );
}
